# Workflow for publishing Pelican site to GitHub Pages.

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Pelican and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ${{ github.event.inputs.requirements }}

      - name: Build Pelican site
        run: |
          pelican content \
            --settings ${{ github.event.inputs.settings }} \
            ${GITHUB_TOKEN:+--write-selected-branches \
            --extra-settings \
            SITEURL='"${{ github.event.inputs.siteurl || github.event.repository.url }}"' \
            FEED_DOMAIN='"${{ github.event.inputs.feed_domain || github.event.repository.url }}"' \
            --output ${{ github.event.inputs.output-path }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.event.inputs.output-path }}
          publish_branch: gh-pages  # Adjust branch name as needed

